# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e680aa8ec76c90b290ef00ef235e58302d01e8ba83c330e83c174eb841f1b5381d2f70833ccf01717a0bce10394bd8906bb80c9099209d6a71888838de2b0d1c

test:
  secret_key_base: d51359c4d0f6ed3b39f1af267e5478bd54d97da282fe70bc2de7bf66ec7a4884a09bcd3a6cd8701c71ae8fe65d959fce7a5f111a045c1021e8d743f15f13e3d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
